spring:
  datasource:
    url: jdbc:mysql://129.204.227.14:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 2017gzMM
logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.macro.mall: debug
    com.macro.mall.demo.service.FeignAdminService: debug